// TypesFromSerializers CacheKey 6a63933c1e11e76a6991d13ff1ef254f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsEdit {
      id: number
      created_at: string | Date
      endpoint: unknown
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
