// TypesFromSerializers CacheKey e713d7824b202218db591bdf4c787aa6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsEdit {
      id: number
      created_at: string | Date
      endpoint: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
