// TypesFromSerializers CacheKey a23309744921bcc9f602b8fcfc74bce2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsFormData {
      id?: number
      endpoint: string
      payload?: string
      title: string
    }
  }
}
