// TypesFromSerializers CacheKey d53acbd5162e9372f8c20d1833fbcb16
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsFormData {
      id?: number
      endpoint: unknown
      payload?: string
      title: string
    }
  }
}
