// TypesFromSerializers CacheKey f9544bba1636ac2db57fdb0182e1fdf0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsIndex {
      id: number
      created_at: string | Date
      endpoint: unknown
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
