// TypesFromSerializers CacheKey 32e0b76a17745eb709c29db66b4e40d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsIndex {
      id: number
      created_at: string | Date
      endpoint: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
