// TypesFromSerializers CacheKey 591dc8bc999147350a905c89ec763485
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsShow {
      id: number
      created_at: string | Date
      endpoint: unknown
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
