// TypesFromSerializers CacheKey 11c64026cef2fd2559033134a4c6ec0e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PayloadsShow {
      id: number
      created_at: string | Date
      endpoint: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
