// TypesFromSerializers CacheKey a810479b2bafabececc736a6c7864af0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandValuesOptions {
      id: number
      label?: string
      value: string
    }
  }
}
