services:
  postgres:
    image: postgres:15.4-alpine 
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  web:
    image: osc_controller
    build: .
    command: >
      bash -c "bin/docker-entrypoint"
    volumes:
      - .:/osc
      - files:/osc/storage
      - secrets:/osc/config/secrets
    ports:
      - "80:3000"
    depends_on:
      - postgres
    environment:
      RACK_ENV: "production"
      RAILS_ENV: "production"
      NODE_ENV: "production"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: postgres
    restart: always

volumes:
  postgres:
  files:
  secrets:
