// TypesFromSerializers CacheKey 019376dd495ab7941ed4a2901fbcd780
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ControlsEdit from '../Controls/Edit'

declare global {
  namespace Schema {
    interface ScreensEdit {
      id: number
      controls: ControlsEdit[]
      created_at: string | Date
      order: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
