// TypesFromSerializers CacheKey c1f54b53dd3c421eb476f40ab9061ef2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensEdit {
      id: number
      created_at: string | Date
      order: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
