// TypesFromSerializers CacheKey c2d68483ee410d3f8b3453eaf7765ec7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ControlsEdit from '../Controls/Edit'

declare global {
  namespace Schema {
    interface ScreensEdit {
      id: number
      columns: number
      controls: ControlsEdit[]
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
