// TypesFromSerializers CacheKey 685aa1ee574b51d0fc12618ffa0417d6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensFormData {
      id?: number
      slug?: string
      columns: number
      order: number
      title: string
    }
  }
}
