// TypesFromSerializers CacheKey de355dee18b22d5aec9e0d7b835f373e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensFormData {
      id?: number
      slug?: string
      order: number
      title: string
    }
  }
}
