// TypesFromSerializers CacheKey 7405c5a81dd8b8135c2d2bd7bc7a351e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensIndex {
      id: number
      columns: number
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
