// TypesFromSerializers CacheKey b2a4396d0b8234e92a0007321119f276
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensIndex {
      id: number
      created_at: string | Date
      order: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
