// TypesFromSerializers CacheKey ec6e9d277254785c3bc9ff38d554bb75
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensOptions {
      id: number
      columns: number
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
