// TypesFromSerializers CacheKey 7200c9fc6bd5c1bc62422383980ebb6c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensOptions {
      id?: number
      order: number
      slug: string
      title: string
    }
  }
}
