// TypesFromSerializers CacheKey f1aa24718f32ef2eca9a0db387fb2097
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensPersisted {
      id: number
      columns: number
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
