// TypesFromSerializers CacheKey 7ee3c5dc791e63115b87c96ec482ed00
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensPersisted {
      id: number
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
