// TypesFromSerializers CacheKey dafad3fdd805d870ad7a24a8884cfdf0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ScreensShow {
      id: number
      created_at: string | Date
      order: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
