// TypesFromSerializers CacheKey b51801aadb0a31a14c1e7ca6c04eb6c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ControlsShow from '../Controls/Show'

declare global {
  namespace Schema {
    interface ScreensShow {
      id: number
      columns: number
      controls: ControlsShow[]
      created_at?: string | Date
      order: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
