// TypesFromSerializers CacheKey 969da6b34a7d5fd14e9680af2812e5aa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ControlsShow from '../Controls/Show'

declare global {
  namespace Schema {
    interface ScreensShow {
      id: number
      controls: ControlsShow[]
      created_at: string | Date
      order: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
