// TypesFromSerializers CacheKey 86721184a9f27404319bdc672e4b837a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersEdit {
      id: number
      created_at: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
