// TypesFromSerializers CacheKey b9145d2c18a0f6fab012d0a76179ab14
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersEdit {
      id: number
      created_at: string | Date
      description?: string
      hostname?: string
      port?: number
      title?: string
      updated_at: string | Date
    }
  }
}
