// TypesFromSerializers CacheKey f339f7c6ee20beabffa34c27dd8b94d5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersEdit {
      id: number
      created_at: string | Date
      description?: string
      hostname?: string
      port?: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
