// TypesFromSerializers CacheKey 06d8f2f3109c83e145dbfacba07430bc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersFormData {
      id?: number
      slug?: unknown
      description?: string
      hostname?: string
      port?: number
      title: string
    }
  }
}
