// TypesFromSerializers CacheKey 84d128d8fe827615484a2b15377c8951
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersFormData {
      id?: number
      slug?: string
      description?: string
      hostname?: string
      port?: number
      title: string
    }
  }
}
