// TypesFromSerializers CacheKey ef420d2ae747b66fa15b13287df7c9c0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersFormData {
      id?: number
      description?: string
      hostname?: string
      port?: number
      title?: string
    }
  }
}
