// TypesFromSerializers CacheKey 49d4f077c9c1fdcd3ea411ac4575561f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersIndex {
      id: number
      created_at?: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
