// TypesFromSerializers CacheKey 716bc833e9c693f93d1559387bf54345
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersIndex {
      id: number
      created_at: string | Date
      description?: string
      hostname?: string
      port?: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
