// TypesFromSerializers CacheKey f4d136286c2e492204840de9b4897383
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersIndex {
      id: number
      created_at: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
