// TypesFromSerializers CacheKey 8b04da4169bb205ea567318e3db33bb1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersOptions {
      id: number
      slug: unknown
      title: string
    }
  }
}
