// TypesFromSerializers CacheKey 0d57d612e5af2c5c1cd9770f8851f247
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersOptions {
      id: number
      slug: string
      title: string
    }
  }
}
