// TypesFromSerializers CacheKey 1849ca7af9fd288fed83589abde6bcbd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersReference {
      id: number
      created_at: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
