// TypesFromSerializers CacheKey 4ae5b1e732eb9c8b762b58f698add65d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersReference {
      id: number
      created_at?: string | Date
      description?: string
      hostname?: string
      port?: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
