// TypesFromSerializers CacheKey 90ce51ce2d383d02ea7971d5cc45d709
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersReference {
      id: number
      created_at?: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
