// TypesFromSerializers CacheKey 0e1bcd426aeffaa0316cee3614771eba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersShow {
      id: number
      created_at?: string | Date
      description?: string
      hostname: string
      port?: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
