// TypesFromSerializers CacheKey 204899a50e30e05058c42e1ae91ce15d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersShow {
      id: number
      created_at?: string | Date
      description?: string
      hostname?: string
      port?: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
