// TypesFromSerializers CacheKey c78937949210a9390a5f121ae6c472e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServersShow {
      id: number
      created_at: string | Date
      description?: string
      hostname?: string
      port?: number
      title?: string
      updated_at: string | Date
    }
  }
}
