// TypesFromSerializers CacheKey f90ea313c47b72cd7b0c592b1fb87ccd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Circle {
      id?: number
      slug?: string
      name?: string
    }
  }
}
