// TypesFromSerializers CacheKey 54e467a0c24e64be3d838c0060ac9555
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandValue {
      id?: number
      command_id: number
      label?: string
      value: string
    }
  }
}
