// TypesFromSerializers CacheKey 88adb943098831eeb50bb3bfe3c418ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Command {
      id?: number
      slug?: string
      description?: string
      message?: string
      payload?: string
      payload_type?: number
      server_id: number
      title: string
    }
  }
}
