// TypesFromSerializers CacheKey 88f5be24386831a44716ba09b0d16df6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from './CommandValue'

declare global {
  namespace Schema {
    interface Command {
      id?: number
      slug?: string
      address?: string
      command_values: CommandValue[]
      description?: string
      payload?: string
      payload_type?: number
      server_id: number
      title: string
    }
  }
}
