// TypesFromSerializers CacheKey 3dcb034764d4532e633f2e19b6f20f2d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from './CommandValue'

declare global {
  namespace Schema {
    interface Command {
      id?: number
      slug?: string
      address?: string
      allow_custom_value: boolean
      command_values: CommandValue[]
      description?: string
      payload_type?: number
      server_id: number
      title: string
    }
  }
}
