// TypesFromSerializers CacheKey 0b7184925c4ab890a57d51528e320abe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandValue {
      id?: number
      label?: string
      value: string
    }
  }
}
