// TypesFromSerializers CacheKey e62bb3d417d0814bb984b360886abfc4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Protocol from './Protocol'

declare global {
  namespace Schema {
    interface Control {
      id?: number
      control_type: string
      max_value?: number
      min_value?: number
      order: number
      protocol: Protocol
      protocol_id: number
      screen_id: number
      title: string
      value?: number
    }
  }
}
