// TypesFromSerializers CacheKey 11440afa5ce58484a6ab36473b4d78fb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Command from './Command'
import type Protocol from './Protocol'

declare global {
  namespace Schema {
    interface Control {
      id?: number
      color?: string
      command: Command
      command_id?: number
      control_type: string
      max_value?: string | number
      min_value?: string | number
      order: number
      protocol: Protocol
      protocol_id?: number
      screen_id: number
      title: string
      value?: string | number
    }
  }
}
