// TypesFromSerializers CacheKey 49ace47c5144019b3e0e1b2a2140afeb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Endpoint {
      id?: number
      description?: string
      server_id: number
      title?: string
      url?: string
    }
  }
}
