// TypesFromSerializers CacheKey 681df80f6c3d19c894755246d30b71de
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Group {
      id?: number
      slug?: string
      circle_id: number
      name: string
    }
  }
}
