// TypesFromSerializers CacheKey 4702faf75dd28e25449903fd40f17b98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Member {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
    }
  }
}
