// TypesFromSerializers CacheKey bc0bca5d88879b27b12dcb08551937e1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Org {
      id?: number
      slug?: string
      description?: string
      name?: string
    }
  }
}
