// TypesFromSerializers CacheKey 5fea7a109aed20c7fe0b8c9933e1d8f0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Payload {
      id?: number
      endpoint: string
      payload?: string
      title: string
    }
  }
}
