// TypesFromSerializers CacheKey 4b6e2302b33a26a3d88730924d663597
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Payload {
      id?: number
      endpoint: unknown
      payload?: string
      title: string
    }
  }
}
