// TypesFromSerializers CacheKey 9e3c27e8a0c4143dbd4cb7397cb6d8a2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
    }
  }
}
