// TypesFromSerializers CacheKey 9f4b20b168689784751478c55ed8227d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Presentation {
      id?: number
      name?: string
      theme_id: number
    }
  }
}
