// TypesFromSerializers CacheKey c4f3985102064c706a7321de6e9b69c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsEdit from './Commands/Edit'

declare global {
  namespace Schema {
    interface Protocol {
      id?: number
      slug?: string
      commands: CommandsEdit[]
      description?: string
      title: string
    }
  }
}
