// TypesFromSerializers CacheKey 6689864ee4769643364f26928fa96ee3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtcolsCommand {
      id?: unknown
      command_id: unknown
      delay: unknown
      protocol_id: unknown
      value: unknown
    }
  }
}
