// TypesFromSerializers CacheKey 0f581865517b2c1dfd184b15339fd3cf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from './CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommand {
      id?: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      delay?: number
      protocol_id: number
      value?: string
    }
  }
}
