// TypesFromSerializers CacheKey e5eb48ce438c5f4c22d9ef0b9fa1b4b7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Protocol {
      id?: number
      description?: string
      title: string
    }
  }
}
