// TypesFromSerializers CacheKey 3569208f9d73da5f9592be2d5ee673fb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Protocol {
      id?: number
      title: string
    }
  }
}
