// TypesFromSerializers CacheKey 6ef2ce1bfe31bdf1de600971fe94191e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from './CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommand {
      id?: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      delay?: number
      order: number
      protocol_id: number
      value?: string
    }
  }
}
