// TypesFromSerializers CacheKey 8c872ff1350dd46eebb5322ff01f09a2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteEndpoint {
      id?: number
      endpoint?: string
      remote_api_id: number
      title?: string
    }
  }
}
