// TypesFromSerializers CacheKey b3cbc500a3ccb8bc9040ca7f3334f93f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteApi {
      id?: number
      auth_token?: string
      description?: string
      root_url?: string
      title?: string
    }
  }
}
