// TypesFromSerializers CacheKey 635505325774f17218367514ca046a12
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from './User'

declare global {
  namespace Schema {
    interface Role {
      id?: number
      created_at: string | Date
      name?: string
      resource_id?: number
      resource_type?: string
      updated_at: string | Date
      users: User[]
    }
  }
}
