// TypesFromSerializers CacheKey d0bd91c8898d25950b0278c2298a0a57
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Screen {
      id?: number
      slug?: string
      order: number
      title: string
    }
  }
}
