// TypesFromSerializers CacheKey 33a407f572702e2df7aedd1e7237838c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Screen {
      id?: number
      slug?: string
      columns: number
      order: number
      title: string
    }
  }
}
