// TypesFromSerializers CacheKey 1d0ebd771dfaa1616c2b8cc2815f3579
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Server {
      id?: number
      slug?: string
      description?: string
      hostname?: string
      port?: number
      title: string
    }
  }
}
