// TypesFromSerializers CacheKey 40aabc61d8d8aa6ed654b56786781183
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Server {
      id?: number
      slug?: string
      description?: string
      hostname: string
      port?: number
      title: string
    }
  }
}
