// TypesFromSerializers CacheKey 4015f5f5cd21de474be56816df44d3b7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Server {
      id?: number
      slug?: unknown
      description?: string
      hostname?: string
      port?: number
      title: string
    }
  }
}
