// TypesFromSerializers CacheKey c838a5a201a009d5bbe8e232e1b0f43b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Theme {
      id?: number
      slug?: string
      circle_id: number
      published_at?: string | Date
      status: number
      title?: string
    }
  }
}
