// TypesFromSerializers CacheKey ebc9b839bbfdcd288e7397ed0c5645b1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface User {
      id?: number
      active: boolean
      email: string
    }
  }
}
