// TypesFromSerializers CacheKey 685966de368d06f5f02f0e976edffb00
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesEdit {
      id: number
      created_at: string | Date
      name?: string
      slug: string
      updated_at: string | Date
    }
  }
}
