// TypesFromSerializers CacheKey 043e25cee9d94e9f54150fdcad3a71dc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesFormData {
      id?: number
      slug?: string
      name?: string
    }
  }
}
