// TypesFromSerializers CacheKey 3f7716a439d5831104658c3fe4fb0f02
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ThemesIndex from '../Themes/Index'

declare global {
  namespace Schema {
    interface CirclesIndex {
      id: number
      created_at: string | Date
      name?: string
      slug: string
      themes: ThemesIndex[]
      updated_at: string | Date
    }
  }
}
