// TypesFromSerializers CacheKey c740904a0e29eff55c33f211add7f379
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesOptions {
      id: number
      name?: string
      slug: string
    }
  }
}
