// TypesFromSerializers CacheKey 7f7c0da02cc61ddd9639ab449442824b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CirclesShare {
      id: number
      name?: string
      slug: string
    }
  }
}
