// TypesFromSerializers CacheKey 25d1f2af4264e41141ec2a25989b5aa7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type MembersShallow from '../Members/Shallow'
import type ThemesShallow from '../Themes/Shallow'

declare global {
  namespace Schema {
    interface CirclesShow {
      id: number
      created_at: string | Date
      members: MembersShallow[]
      name?: string
      slug: string
      themes: ThemesShallow[]
      updated_at: string | Date
    }
  }
}
