// TypesFromSerializers CacheKey 6b8a352fa80e9172e3f9ad4870b89c25
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersEdit {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
