// TypesFromSerializers CacheKey 49fb14429e6b4572d49b564820da609e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersFormData {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
    }
  }
}
