// TypesFromSerializers CacheKey 023b5198e19ae1393fff659a79ecb2bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersIndex {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
