// TypesFromSerializers CacheKey 0b6ab8591dea3bd02d4ed1c0c08b36dc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShallow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
