// TypesFromSerializers CacheKey d5ed3f17c9a2d51828241c48d747a066
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface MembersShow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      number?: string
      slug: string
      updated_at: string | Date
    }
  }
}
