// TypesFromSerializers CacheKey c20fc8ded23cd0c60c181fe697415ea5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesEdit {
      id: number
      circle_id: number
      created_at: string | Date
      published_at?: string | Date
      slug: string
      status: number
      title?: string
      updated_at: string | Date
    }
  }
}
