// TypesFromSerializers CacheKey 3198654a91a4bb7f3cc3f1dc19b2a4d8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesFormData {
      id?: number
      slug?: string
      circle_id: number
      published_at?: string | Date
      status: number
      title?: string
    }
  }
}
