// TypesFromSerializers CacheKey 276d6754f797bea27fe75ed6f5256cc2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesIndex {
      id: number
      circle_id: number
      created_at: string | Date
      published_at?: string | Date
      slug: string
      status: number
      title?: string
      updated_at: string | Date
    }
  }
}
