// TypesFromSerializers CacheKey 3dcbea4193c2f526e90a81f0276b07ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ThemesShallow {
      id: number
      circle_id: number
      created_at: string | Date
      published_at?: string | Date
      slug: string
      status: number
      title?: string
      updated_at: string | Date
    }
  }
}
