// TypesFromSerializers CacheKey 8f9ef31ca631d52ac4eb99cb2d22cb58
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsEdit {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at?: string | Date
      delay?: number
      order: number
      protocol_id: number
      updated_at?: string | Date
      value?: string
    }
  }
}
