// TypesFromSerializers CacheKey cce2571b389919c0d8660e7427aadd31
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsEdit {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at: string | Date
      delay?: number
      protocol_id: number
      updated_at: string | Date
      value?: string
    }
  }
}
