// TypesFromSerializers CacheKey 434ced89f9e439cff25b30b19b54afd3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsFormData {
      id?: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      delay?: number
      order: number
      protocol_id: number
      value?: string
    }
  }
}
