// TypesFromSerializers CacheKey 5b0e4b31070fef4df4f7f9e255b5a2e8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsFormData {
      id?: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      delay?: number
      key: unknown
      order: number
      protocol_id: number
      value?: string
    }
  }
}
