// TypesFromSerializers CacheKey 623aaca8e3272a94b3e14c6a3c86cc39
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsFormData {
      id?: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      delay?: number
      protocol_id: number
      value?: string
    }
  }
}
