// TypesFromSerializers CacheKey 279bfc5be533514a1be4c45bd0d5f806
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsIndex {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at?: string | Date
      delay?: number
      order: number
      protocol_id: number
      updated_at?: string | Date
      value?: string
    }
  }
}
