// TypesFromSerializers CacheKey 4cb3aeeb87f65bf9b59517b30ae16365
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsIndex {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at: string | Date
      delay?: number
      order: number
      protocol_id: number
      updated_at: string | Date
      value?: string
    }
  }
}
