// TypesFromSerializers CacheKey 5f73a252fc57b5de5bb77e45fbdc2ccb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsIndex {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at: string | Date
      delay?: number
      protocol_id: number
      updated_at: string | Date
      value?: string
    }
  }
}
