// TypesFromSerializers CacheKey 3164a930b33c1d33bd30d1092cd3076e
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsShow {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at: string | Date
      delay?: number
      protocol_id: number
      updated_at: string | Date
      value?: string
    }
  }
}
