// TypesFromSerializers CacheKey b8a0df1e287fb0a00fea24aed26631c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsShow {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at?: string | Date
      delay?: number
      order: number
      protocol_id: number
      updated_at?: string | Date
      value?: string
    }
  }
}
