// TypesFromSerializers CacheKey 667843e03b6448df9d74c8d728d57c0f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface ProtocolsCommandsShow {
      id: number
      command_id: number
      command_value: CommandValue
      command_value_id?: number
      created_at: string | Date
      delay?: number
      order: number
      protocol_id: number
      updated_at: string | Date
      value?: string
    }
  }
}
