// TypesFromSerializers CacheKey 54ab64ee349a71bb3bd5ddc2c22198eb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsEdit {
      id: number
      created_at: string | Date
      description?: string
      message?: string
      payload?: string
      payload_type?: number
      server_id: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
