// TypesFromSerializers CacheKey c7b54a2b34026d6bfd1663b3542b1db6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsEdit {
      id: number
      created_at: string | Date
      description?: string
      message?: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
