// TypesFromSerializers CacheKey f6e97c0c4ad3b5a0c700b4968b01d6a7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsFormData {
      id?: number
      endpoint: unknown
      payload?: string
      title: string
    }
  }
}
