// TypesFromSerializers CacheKey c5e027a014ad0df13434a2ac4687f443
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsFormData {
      id?: number
      description?: string
      message?: string
      payload?: string
      title: string
    }
  }
}
