// TypesFromSerializers CacheKey 0a071009c3de4ff49602b94265fdc625
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsIndex {
      id: number
      created_at: string | Date
      description?: string
      message?: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
