// TypesFromSerializers CacheKey da9bc249006e9a82296d1ec5bb9e19fa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface CommandsIndex {
      id: number
      address?: string
      allow_custom_value: boolean
      command_values: CommandValue[]
      created_at?: string | Date
      description?: string
      payload_type: "integer" | "float" | "string" | "blob" | "time" | "symbol" | "character" | "boolean"
      server_id: number
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
