// TypesFromSerializers CacheKey b9853cbc85686568b030365fa113f4ef
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface CommandsIndex {
      id: number
      address?: string
      command_values: CommandValue[]
      created_at: string | Date
      description?: string
      payload?: string
      payload_type?: number
      server_id: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
