// TypesFromSerializers CacheKey cd29a10b057df24ec19f5e98bfae959f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsOptions {
      id?: number
      slug?: string
      address?: string
      allow_custom_value: boolean
      description?: string
      payload_type?: number
      server_id: number
      title: string
    }
  }
}
