// TypesFromSerializers CacheKey b152bb165613d3ca4dec4f03a2c3dfe8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsOptions {
      id: number
      address?: string
      allow_custom_value: boolean
      description?: string
      payload_type?: number
      server_id: number
      slug: string
      title: string
    }
  }
}
