// TypesFromSerializers CacheKey 53fb4e1e497ae4eb821472a77bfc946d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ServersReference from '../Servers/Reference'
import type CommandValue from '../CommandValue'

declare global {
  namespace Schema {
    interface CommandsProtocol {
      id: number
      address?: string
      created_at: string | Date
      description?: string
      payload?: string
      payload_type?: number
      server: ServersReference
      server_id: number
      slug: string
      title: string
      updated_at: string | Date
      values: CommandValue[]
    }
  }
}
