// TypesFromSerializers CacheKey dd3174e7e9d13e95e45591cdb223907d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type ServersReference from '../Servers/Reference'

declare global {
  namespace Schema {
    interface CommandsProtocol {
      id: number
      address?: string
      command_values: CommandValue[]
      created_at: string | Date
      description?: string
      payload?: string
      payload_type?: number
      server: ServersReference
      server_id: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
