// TypesFromSerializers CacheKey 5d92b6e8e95b9d137243f8e46c1d3c32
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type ProtocolsOptions from '../Protocols/Options'
import type ServersReference from '../Servers/Reference'

declare global {
  namespace Schema {
    interface CommandsShow {
      id: number
      address?: string
      allow_custom_value: boolean
      command_values: CommandValue[]
      created_at: string | Date
      description?: string
      payload_type?: number
      protocols: ProtocolsOptions[]
      server: ServersReference
      server_id: number
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
