// TypesFromSerializers CacheKey 288cc08c3542f0f457d20d01bcc0cde6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsShow {
      id: number
      created_at: string | Date
      endpoint: unknown
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
