// TypesFromSerializers CacheKey 825f6414fce45af087c974a6dbe56bb7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CommandsShow {
      id: number
      created_at: string | Date
      description?: string
      message?: string
      payload?: string
      title: string
      updated_at: string | Date
    }
  }
}
