require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/commands", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Command. As you add validations to Command, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Command.create! valid_attributes
      get commands_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      command = Command.create! valid_attributes
      get command_url(command)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_command_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      command = Command.create! valid_attributes
      get edit_command_url(command)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Command" do
        expect {
          post commands_url, params: { command: valid_attributes }
        }.to change(Command, :count).by(1)
      end

      it "redirects to the created command" do
        post commands_url, params: { command: valid_attributes }
        expect(response).to redirect_to(command_url(Command.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Command" do
        expect {
          post commands_url, params: { command: invalid_attributes }
        }.not_to change(Command, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post commands_url, params: { command: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested command" do
        command = Command.create! valid_attributes
        patch command_url(command), params: { command: new_attributes }
        command.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the command" do
        command = Command.create! valid_attributes
        patch command_url(command), params: { command: new_attributes }
        command.reload
        expect(response).to redirect_to(command_url(command))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        command = Command.create! valid_attributes
        patch command_url(command), params: { command: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested command" do
      command = Command.create! valid_attributes
      expect {
        delete command_url(command)
      }.to change(Command, :count).by(-1)
    end

    it "redirects to the commands list" do
      command = Command.create! valid_attributes
      delete command_url(command)
      expect(response).to redirect_to(commands_url)
    end
  end
end
