require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/controls", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Control. As you add validations to Control, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Control.create! valid_attributes
      get controls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      control = Control.create! valid_attributes
      get control_url(control)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_control_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      control = Control.create! valid_attributes
      get edit_control_url(control)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Control" do
        expect {
          post controls_url, params: { control: valid_attributes }
        }.to change(Control, :count).by(1)
      end

      it "redirects to the created control" do
        post controls_url, params: { control: valid_attributes }
        expect(response).to redirect_to(control_url(Control.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Control" do
        expect {
          post controls_url, params: { control: invalid_attributes }
        }.to change(Control, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post controls_url, params: { control: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested control" do
        control = Control.create! valid_attributes
        patch control_url(control), params: { control: new_attributes }
        control.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the control" do
        control = Control.create! valid_attributes
        patch control_url(control), params: { control: new_attributes }
        control.reload
        expect(response).to redirect_to(control_url(control))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        control = Control.create! valid_attributes
        patch control_url(control), params: { control: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested control" do
      control = Control.create! valid_attributes
      expect {
        delete control_url(control)
      }.to change(Control, :count).by(-1)
    end

    it "redirects to the controls list" do
      control = Control.create! valid_attributes
      delete control_url(control)
      expect(response).to redirect_to(controls_url)
    end
  end
end
