require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/protocols_payloads", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ProtocolsPayload. As you add validations to ProtocolsPayload, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ProtocolsPayload.create! valid_attributes
      get protocols_payloads_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      protocols_payload = ProtocolsPayload.create! valid_attributes
      get protocols_payload_url(protocols_payload)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_protocols_payload_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      protocols_payload = ProtocolsPayload.create! valid_attributes
      get edit_protocols_payload_url(protocols_payload)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ProtocolsPayload" do
        expect {
          post protocols_payloads_url, params: { protocols_payload: valid_attributes }
        }.to change(ProtocolsPayload, :count).by(1)
      end

      it "redirects to the created protocols_payload" do
        post protocols_payloads_url, params: { protocols_payload: valid_attributes }
        expect(response).to redirect_to(protocols_payload_url(ProtocolsPayload.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ProtocolsPayload" do
        expect {
          post protocols_payloads_url, params: { protocols_payload: invalid_attributes }
        }.to change(ProtocolsPayload, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post protocols_payloads_url, params: { protocols_payload: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested protocols_payload" do
        protocols_payload = ProtocolsPayload.create! valid_attributes
        patch protocols_payload_url(protocols_payload), params: { protocols_payload: new_attributes }
        protocols_payload.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the protocols_payload" do
        protocols_payload = ProtocolsPayload.create! valid_attributes
        patch protocols_payload_url(protocols_payload), params: { protocols_payload: new_attributes }
        protocols_payload.reload
        expect(response).to redirect_to(protocols_payload_url(protocols_payload))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        protocols_payload = ProtocolsPayload.create! valid_attributes
        patch protocols_payload_url(protocols_payload), params: { protocols_payload: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested protocols_payload" do
      protocols_payload = ProtocolsPayload.create! valid_attributes
      expect {
        delete protocols_payload_url(protocols_payload)
      }.to change(ProtocolsPayload, :count).by(-1)
    end

    it "redirects to the protocols_payloads list" do
      protocols_payload = ProtocolsPayload.create! valid_attributes
      delete protocols_payload_url(protocols_payload)
      expect(response).to redirect_to(protocols_payloads_url)
    end
  end
end
