require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/remote_endpoints", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RemoteEndpoint. As you add validations to RemoteEndpoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RemoteEndpoint.create! valid_attributes
      get remote_endpoints_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      remote_endpoint = RemoteEndpoint.create! valid_attributes
      get remote_endpoint_url(remote_endpoint)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_remote_endpoint_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      remote_endpoint = RemoteEndpoint.create! valid_attributes
      get edit_remote_endpoint_url(remote_endpoint)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RemoteEndpoint" do
        expect {
          post remote_endpoints_url, params: { remote_endpoint: valid_attributes }
        }.to change(RemoteEndpoint, :count).by(1)
      end

      it "redirects to the created remote_endpoint" do
        post remote_endpoints_url, params: { remote_endpoint: valid_attributes }
        expect(response).to redirect_to(remote_endpoint_url(RemoteEndpoint.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RemoteEndpoint" do
        expect {
          post remote_endpoints_url, params: { remote_endpoint: invalid_attributes }
        }.to change(RemoteEndpoint, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post remote_endpoints_url, params: { remote_endpoint: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested remote_endpoint" do
        remote_endpoint = RemoteEndpoint.create! valid_attributes
        patch remote_endpoint_url(remote_endpoint), params: { remote_endpoint: new_attributes }
        remote_endpoint.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the remote_endpoint" do
        remote_endpoint = RemoteEndpoint.create! valid_attributes
        patch remote_endpoint_url(remote_endpoint), params: { remote_endpoint: new_attributes }
        remote_endpoint.reload
        expect(response).to redirect_to(remote_endpoint_url(remote_endpoint))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        remote_endpoint = RemoteEndpoint.create! valid_attributes
        patch remote_endpoint_url(remote_endpoint), params: { remote_endpoint: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested remote_endpoint" do
      remote_endpoint = RemoteEndpoint.create! valid_attributes
      expect {
        delete remote_endpoint_url(remote_endpoint)
      }.to change(RemoteEndpoint, :count).by(-1)
    end

    it "redirects to the remote_endpoints list" do
      remote_endpoint = RemoteEndpoint.create! valid_attributes
      delete remote_endpoint_url(remote_endpoint)
      expect(response).to redirect_to(remote_endpoints_url)
    end
  end
end
