require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/remote_apis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RemoteApi. As you add validations to RemoteApi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RemoteApi.create! valid_attributes
      get remote_apis_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      remote_api = RemoteApi.create! valid_attributes
      get remote_api_url(remote_api)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_remote_api_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      remote_api = RemoteApi.create! valid_attributes
      get edit_remote_api_url(remote_api)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RemoteApi" do
        expect {
          post remote_apis_url, params: { remote_api: valid_attributes }
        }.to change(RemoteApi, :count).by(1)
      end

      it "redirects to the created remote_api" do
        post remote_apis_url, params: { remote_api: valid_attributes }
        expect(response).to redirect_to(remote_api_url(RemoteApi.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RemoteApi" do
        expect {
          post remote_apis_url, params: { remote_api: invalid_attributes }
        }.to change(RemoteApi, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post remote_apis_url, params: { remote_api: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested remote_api" do
        remote_api = RemoteApi.create! valid_attributes
        patch remote_api_url(remote_api), params: { remote_api: new_attributes }
        remote_api.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the remote_api" do
        remote_api = RemoteApi.create! valid_attributes
        patch remote_api_url(remote_api), params: { remote_api: new_attributes }
        remote_api.reload
        expect(response).to redirect_to(remote_api_url(remote_api))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        remote_api = RemoteApi.create! valid_attributes
        patch remote_api_url(remote_api), params: { remote_api: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested remote_api" do
      remote_api = RemoteApi.create! valid_attributes
      expect {
        delete remote_api_url(remote_api)
      }.to change(RemoteApi, :count).by(-1)
    end

    it "redirects to the remote_apis list" do
      remote_api = RemoteApi.create! valid_attributes
      delete remote_api_url(remote_api)
      expect(response).to redirect_to(remote_apis_url)
    end
  end
end
