require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/screens", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Screen. As you add validations to Screen, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Screen.create! valid_attributes
      get screens_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      screen = Screen.create! valid_attributes
      get screen_url(screen)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      screen = Screen.create! valid_attributes
      get edit_screen_url(screen)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Screen" do
        expect {
          post screens_url, params: { screen: valid_attributes }
        }.to change(Screen, :count).by(1)
      end

      it "redirects to the created screen" do
        post screens_url, params: { screen: valid_attributes }
        expect(response).to redirect_to(screen_url(Screen.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Screen" do
        expect {
          post screens_url, params: { screen: invalid_attributes }
        }.not_to change(Screen, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post screens_url, params: { screen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested screen" do
        screen = Screen.create! valid_attributes
        patch screen_url(screen), params: { screen: new_attributes }
        screen.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the screen" do
        screen = Screen.create! valid_attributes
        patch screen_url(screen), params: { screen: new_attributes }
        screen.reload
        expect(response).to redirect_to(screen_url(screen))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        screen = Screen.create! valid_attributes
        patch screen_url(screen), params: { screen: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested screen" do
      screen = Screen.create! valid_attributes
      expect {
        delete screen_url(screen)
      }.to change(Screen, :count).by(-1)
    end

    it "redirects to the screens list" do
      screen = Screen.create! valid_attributes
      delete screen_url(screen)
      expect(response).to redirect_to(screens_url)
    end
  end
end
