// TypesFromSerializers CacheKey 196cc80936df3356859b0d8c395d986d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteApisEdit {
      id: number
      auth_token?: string
      created_at: string | Date
      description?: string
      root_url?: string
      title?: string
      updated_at: string | Date
    }
  }
}
