// TypesFromSerializers CacheKey fa4864ed865260d29dca68ea3a909d3b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteApisFormData {
      id?: number
      auth_token?: string
      description?: string
      root_url?: string
      title?: string
    }
  }
}
