// TypesFromSerializers CacheKey d1f59e4cf684dcbf9000636a2ad37e87
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteApisIndex {
      id: number
      auth_token?: string
      created_at: string | Date
      description?: string
      root_url?: string
      title?: string
      updated_at: string | Date
    }
  }
}
