// TypesFromSerializers CacheKey 95b745673b6e6bb1ce61086cb41b454b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteApisShow {
      id: number
      auth_token?: string
      created_at: string | Date
      description?: string
      root_url?: string
      title?: string
      updated_at: string | Date
    }
  }
}
