// TypesFromSerializers CacheKey 0c5968dcd70773f1053bb79c14064e9b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsEdit {
      id: number
      circle_id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
