// TypesFromSerializers CacheKey 8417955369e0e068156e7a28d008964c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsFormData {
      id?: number
      name: string
    }
  }
}
