// TypesFromSerializers CacheKey ef262fa51f223d53b104c7dcc1059800
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsIndex {
      id: number
      circle_id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
