// TypesFromSerializers CacheKey c8a60c7b0f3c5a2966f96030ad12e6d0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface GroupsShow {
      id: number
      circle_id: number
      created_at: string | Date
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
