// TypesFromSerializers CacheKey 03c2762ad94f1378106a278397892a4b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: number
      active: boolean
      created_at?: string | Date
      email: string
      roles: Role[]
      updated_at?: string | Date
    }
  }
}
