// TypesFromSerializers CacheKey 562af8bcf3f33ae367e572a3b9b2674c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: number
      active: boolean
      email: string
    }
  }
}
