// TypesFromSerializers CacheKey dfe821eb987d3754764212ca26efdbea
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserPreferences from '../../IUserPreferences'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: number
      active: boolean
      created_at?: string | Date
      email: string
      roles: Role[]
      updated_at?: string | Date
      user_preferences: IUserPreferences
    }
  }
}
