// TypesFromSerializers CacheKey cdcfbb1023385f08d1cd57c45c4fba7a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserTablePreferences from '../../IUserTablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type CirclesShare from '../Circles/Share'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersIndex {
      id: number
      active: boolean
      circles: CirclesShare[]
      confirmation_sent_at?: string | Date
      confirmation_token?: string
      confirmed_at?: string | Date
      created_at: string | Date
      current_sign_in_at?: string | Date
      current_sign_in_ip?: string
      email: string
      encrypted_password: string
      failed_attempts: number
      invitation_accepted_at?: string | Date
      invitation_created_at?: string | Date
      invitation_limit?: number
      invitation_sent_at?: string | Date
      invitation_token?: string
      invitations_count: number
      invited_by_id?: number
      invited_by_type?: string
      last_sign_in_at?: string | Date
      last_sign_in_ip?: string
      locked_at?: string | Date
      person: Person
      person_id?: number
      remember_created_at?: string | Date
      reset_password_sent_at?: string | Date
      reset_password_token?: string
      roles: Role[]
      sign_in_count: number
      table_preferences: IUserTablePreferences
      unconfirmed_email?: string
      unlock_token?: string
      updated_at: string | Date
      user_preferences: IUserPreferences
    }
  }
}
