// TypesFromSerializers CacheKey bdad1f99c5e6e5a670de4af97ef239b0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserPreferences from '../../IUserPreferences'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShare {
      id: unknown
      created_at: unknown
      roles: Role[]
      updated_at: unknown
      user_preferences: IUserPreferences
    }
  }
}
