// TypesFromSerializers CacheKey b0991620a5e40270101b1633daa15471
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ITablePreferences from '../../ITablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShare {
      id: number
      active: boolean
      created_at: string | Date
      email: string
      roles: Role[]
      table_preferences: ITablePreferences
      updated_at: string | Date
      user_preferences: IUserPreferences
    }
  }
}
