// TypesFromSerializers CacheKey 836de138b53183779ba95b2d8d7190f8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserTablePreferences from '../../IUserTablePreferences'
import type IUserPreferences from '../../IUserPreferences'
import type CirclesShare from '../Circles/Share'
import type Person from '../Person'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShare {
      id: unknown
      circles: CirclesShare[]
      created_at: unknown
      person: Person
      roles: Role[]
      table_preferences: IUserTablePreferences
      updated_at: unknown
      user_preferences: IUserPreferences
    }
  }
}
