// TypesFromSerializers CacheKey d3e826a4728e0f4016952ab574def02c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type IUserPreferences from '../../IUserPreferences'
import type Role from '../Role'

declare global {
  namespace Schema {
    interface UsersShow {
      id: number
      active: boolean
      created_at: string | Date
      email: string
      roles: Role[]
      updated_at: string | Date
      user_preferences: IUserPreferences
    }
  }
}
