// TypesFromSerializers CacheKey 7e8e6242b1d21fe07b2be0a90ffd25df
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsEdit {
      id: number
      created_at: string | Date
      name?: string
      theme_id: number
      updated_at: string | Date
    }
  }
}
