// TypesFromSerializers CacheKey b0aee9a3dfa8a9fa573f9e990a015021
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsFormData {
      id?: number
      name?: string
      theme_id: number
    }
  }
}
