// TypesFromSerializers CacheKey 940a95e83725e8baac725364ddb136ba
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsIndex {
      id: number
      created_at: string | Date
      name?: string
      theme_id: number
      updated_at: string | Date
    }
  }
}
