// TypesFromSerializers CacheKey aa158a1008c498c435d1ea7b2ac02c63
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsShallow {
      id: number
      created_at: string | Date
      name?: string
      theme_id: number
      updated_at: string | Date
    }
  }
}
