// TypesFromSerializers CacheKey af5cf095319ce97619b35b0df286b6ec
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PresentationsShow {
      id: number
      created_at: string | Date
      name?: string
      theme_id: number
      updated_at: string | Date
    }
  }
}
