// TypesFromSerializers CacheKey 503c6b95a20780fbffffae6761aa1e36
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OrgsFormData {
      id?: number
      description?: string
      name?: string
      slug: string
    }
  }
}
