// TypesFromSerializers CacheKey a42ba682273ff6f98c428f01f2a45ebe
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EndpointsEdit {
      id: number
      created_at: string | Date
      description?: string
      server_id: number
      title?: string
      updated_at: string | Date
      url?: string
    }
  }
}
