// TypesFromSerializers CacheKey 717c80905758fed42602260ec48ef035
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EndpointsFormData {
      id?: number
      description?: string
      server_id: number
      title?: string
      url?: string
    }
  }
}
