// TypesFromSerializers CacheKey 13c9f24be1dda58044e7834fb9f2d256
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EndpointsIndex {
      id: number
      created_at: string | Date
      description?: string
      server_id: number
      title?: string
      updated_at: string | Date
      url?: string
    }
  }
}
