// TypesFromSerializers CacheKey aecfd6decd567d11252a0fa021d8611a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface EndpointsShow {
      id: number
      created_at: string | Date
      description?: string
      server_id: number
      title?: string
      updated_at: string | Date
      url?: string
    }
  }
}
