// TypesFromSerializers CacheKey 139fddf0cf316ba9e74410f517fb2940
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsEdit from '../Commands/Edit'

declare global {
  namespace Schema {
    interface ControlsEdit {
      id: number
      commands: CommandsEdit[]
      control_type: string
      created_at: string | Date
      max_value?: number
      min_value?: number
      order: number
      protocol_id: number
      screen_id: number
      title: string
      updated_at: string | Date
      value?: number
    }
  }
}
