// TypesFromSerializers CacheKey 40ad68244c36ab2957b57127eb042ccc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsEdit from '../Commands/Edit'
import type ProtocolsEdit from '../Protocols/Edit'

declare global {
  namespace Schema {
    interface ControlsEdit {
      id: number
      color?: string
      command: CommandsEdit
      command_id?: number
      control_type: "button" | "slider" | "spacer"
      max_value?: string | number
      min_value?: string | number
      order?: number
      protocol: ProtocolsEdit
      protocol_id?: number
      screen_id: number
      title?: string
      value?: string | number
    }
  }
}
