// TypesFromSerializers CacheKey 3c0e8191e2fdca39c2ae682788d866ea
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Command from '../Command'
import type ProtocolsEdit from '../Protocols/Edit'

declare global {
  namespace Schema {
    interface ControlsEdit {
      id: number
      color?: string
      command: Command
      command_id?: number
      control_type: string
      created_at: string | Date
      max_value?: number
      min_value?: number
      order: number
      protocol: ProtocolsEdit
      protocol_id?: number
      screen_id: number
      title: string
      updated_at: string | Date
      value?: number
    }
  }
}
