// TypesFromSerializers CacheKey 6db9bfdba474b44f5362691dab5b7bfd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsFormData from '../Commands/FormData'
import type ProtocolsFormData from '../Protocols/FormData'

declare global {
  namespace Schema {
    interface ControlsFormData {
      id?: number
      command: CommandsFormData
      command_id?: number
      control_type: string
      max_value?: number
      min_value?: number
      order: number
      protocol: ProtocolsFormData
      protocol_id?: number
      screen_id: number
      title: string
      value?: number
    }
  }
}
