// TypesFromSerializers CacheKey 37cff8a2614851e20ca11699c31bc654
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsFormData from '../Commands/FormData'
import type ProtocolsFormData from '../Protocols/FormData'

declare global {
  namespace Schema {
    interface ControlsFormData {
      id?: number
      color?: string
      command?: CommandsFormData
      command_id?: number
      control_type: "button" | "slider" | "spacer"
      max_value?: string | number
      min_value?: string | number
      order?: number
      protocol?: ProtocolsFormData
      protocol_id?: number
      screen_id: number
      title?: string
      value?: string | number
    }
  }
}
