// TypesFromSerializers CacheKey aa33750f1db2ac36911f93c94f3ef3c7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Command from '../Command'
import type Protocol from '../Protocol'

declare global {
  namespace Schema {
    interface ControlsIndex {
      id: number
      command: Command
      command_id?: number
      control_type: string
      created_at: string | Date
      max_value?: number
      min_value?: number
      order: number
      protocol: Protocol
      protocol_id?: number
      screen_id: number
      title: string
      updated_at: string | Date
      value?: number
    }
  }
}
