// TypesFromSerializers CacheKey 2b10e1e071da5e510056bc5ab5d2ba2f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ControlsIndex {
      id: number
      control_type: string
      created_at: string | Date
      max_value?: number
      min_value?: number
      order: number
      protocol_id: number
      screen_id: number
      title: string
      updated_at: string | Date
      value?: number
    }
  }
}
