// TypesFromSerializers CacheKey ac40fd3d0326778555f4f2b5dc521ed3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ControlsOptions {
      id: number
      color?: string
      command_id?: number
      control_type: string
      max_value?: number
      min_value?: number
      order: number
      protocol_id?: number
      screen_id: number
      title: string
      value?: number
    }
  }
}
