// TypesFromSerializers CacheKey d0135f0bca5ff72e1f267b5c80351abb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ControlsOptions {
      id: number
      color?: string
      command_id?: number
      control_type: string
      max_value?: string | number
      min_value?: string | number
      order: number
      protocol_id?: number
      screen_id: number
      title: string
      value?: string | number
    }
  }
}
