// TypesFromSerializers CacheKey beaa26cca3c569597fc1c361e71f4c6f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Command from '../Command'
import type Protocol from '../Protocol'

declare global {
  namespace Schema {
    interface ControlsShow {
      id: number
      color?: string
      command?: Command
      command_id?: number
      control_type: string
      created_at?: string | Date
      max_value?: string | number
      min_value?: string | number
      order: number
      protocol?: Protocol
      protocol_id?: number
      screen_id: number
      title: string
      updated_at?: string | Date
      value?: string | number
    }
  }
}
