// TypesFromSerializers CacheKey 4de7eaf6c6907eb3f9bef18741e4d438
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsShow from '../Commands/Show'
import type ProtocolsShow from '../Protocols/Show'

declare global {
  namespace Schema {
    interface ControlsShow {
      id: number
      color?: string
      command: CommandsShow
      command_id?: number
      control_type: string
      created_at: string | Date
      max_value?: number
      min_value?: number
      order: number
      protocol: ProtocolsShow
      protocol_id?: number
      screen_id: number
      title: string
      updated_at: string | Date
      value?: number
    }
  }
}
