// TypesFromSerializers CacheKey f7968f7c99488edbc7837d9f8b8a3130
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ControlsShow {
      id: number
      created_at: string | Date
      max_value?: number
      min_value?: number
      position: unknown
      protocol_id: number
      screen_id: number
      title: string
      type: number
      updated_at: string | Date
      value?: number
    }
  }
}
