// TypesFromSerializers CacheKey 09e1d334d0b94d2df7f26693adfe5ebc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      updated_at: string | Date
      user: User
    }
  }
}
