// TypesFromSerializers CacheKey 4761cc083a3b39069899d954209c1b74
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: number
      slug?: string
      active: boolean
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
    }
  }
}
