// TypesFromSerializers CacheKey ce10cafa723ee8b9ba71ea332d0bd1d4
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      updated_at: string | Date
    }
  }
}
