// TypesFromSerializers CacheKey 7d35a2af0992fe0f6855af3a950f2e2b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      middle_name?: string
      name: string
      slug: string
      updated_at: string | Date
      user: User
    }
  }
}
