// TypesFromSerializers CacheKey 30ea254e6dd4f98dbe837107c6153244
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type ServersReference from '../Servers/Reference'

declare global {
  namespace Schema {
    interface ProtocolsCommands {
      id: number
      address?: string
      allow_custom_value: boolean
      command_value_id: number
      command_values: CommandValue[]
      description?: string
      order: unknown
      payload_type?: number
      server: ServersReference
      server_id: number
      slug: string
      title: string
      value: string
    }
  }
}
