// TypesFromSerializers CacheKey 248114b76cd7bc0eafbd27dcc3642d98
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type ServersReference from '../Servers/Reference'

declare global {
  namespace Schema {
    interface ProtocolsCommands {
      id: number
      address?: string
      allow_custom_value: boolean
      command_values: CommandValue[]
      description?: string
      order: unknown
      payload_type?: number
      server: ServersReference
      server_id: number
      slug: string
      title: string
    }
  }
}
