// TypesFromSerializers CacheKey 96b613990ba9c8a4beba0b913201a314
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type ServersReference from '../Servers/Reference'

declare global {
  namespace Schema {
    interface ProtocolsCommands {
      id: number
      address?: string
      allow_custom_value: boolean
      command_value_id: number
      command_values: CommandValue[]
      description?: string
      order: unknown
      payload_type: "integer" | "float" | "string" | "blob" | "time" | "symbol" | "character" | "boolean"
      server: ServersReference
      server_id: number
      slug: string
      title: string
      value: string
    }
  }
}
