// TypesFromSerializers CacheKey dd8c84e1a9b2597fc9a851bea00ff1c3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtocolsEdit {
      id: number
      created_at: string | Date
      description?: string
      title: string
      updated_at: string | Date
    }
  }
}
