// TypesFromSerializers CacheKey a9b20052695d91508820dd079dee245c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsFormData from '../Commands/FormData'
import type ProtocolsCommandsFormData from '../ProtocolsCommands/FormData'

declare global {
  namespace Schema {
    interface ProtocolsEdit {
      id: number
      commands: CommandsFormData[]
      created_at: string | Date
      description?: string
      protocols_commands: ProtocolsCommandsFormData[]
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
