// TypesFromSerializers CacheKey 297f988563cfb99248281ed49b6e1a7c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtocolsEdit {
      id: number
      created_at: string | Date
      title: string
      updated_at: string | Date
    }
  }
}
