// TypesFromSerializers CacheKey 2e225577c6d234dd8d27bb642fad7f42
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsEdit from '../Commands/Edit'

declare global {
  namespace Schema {
    interface ProtocolsFormData {
      id?: number
      slug?: string
      commands: CommandsEdit[]
      description?: string
      title: string
    }
  }
}
