// TypesFromSerializers CacheKey 3bd47c3b8c64511c9dc21bd2b91873cf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandValue from '../CommandValue'
import type CommandsFormData from '../Commands/FormData'

declare global {
  namespace Schema {
    interface ProtocolsFormData {
      id?: number
      slug?: string
      command_values: CommandValue[]
      commands: CommandsFormData[]
      description?: string
      title: string
    }
  }
}
