// TypesFromSerializers CacheKey d9ad963b15e4844729e4616ab751e262
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtocolsIndex {
      id: number
      created_at: string | Date
      description?: string
      title: string
      updated_at: string | Date
    }
  }
}
