// TypesFromSerializers CacheKey b6cdcd1f70d4bcd44181ecf41e97c6bb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtocolsIndex {
      id: number
      created_at: string | Date
      title: string
      updated_at: string | Date
    }
  }
}
