// TypesFromSerializers CacheKey 9eab4f5f0e6ccadb5510feac9eac8f19
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsEdit from '../Commands/Edit'

declare global {
  namespace Schema {
    interface ProtocolsIndex {
      id: number
      commands: CommandsEdit[]
      created_at: string | Date
      description?: string
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
