// TypesFromSerializers CacheKey 10d6f1938d464a3f03c195a29766a289
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtocolsOptions {
      id: number
      description?: string
      slug: string
      title: string
    }
  }
}
