// TypesFromSerializers CacheKey 0747e4f65e0c7409239eba83b323122d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsProtocol from '../Commands/Protocol'

declare global {
  namespace Schema {
    interface ProtocolsOptions {
      id: number
      commands: CommandsProtocol[]
      description?: string
      slug: string
      title: string
    }
  }
}
