// TypesFromSerializers CacheKey 94ecece1d3e3572b6d09eae4bae88b99
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ProtocolsCommands from './Commands'

declare global {
  namespace Schema {
    interface ProtocolsShow {
      id: number
      commands: ProtocolsCommands[]
      created_at?: string | Date
      description?: string
      slug: string
      title: string
      updated_at?: string | Date
    }
  }
}
