// TypesFromSerializers CacheKey 769c08a77763c163f07ddf9ff5ddffbc
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type ProtocolsCommands from './Commands'

declare global {
  namespace Schema {
    interface ProtocolsShow {
      id: number
      commands: ProtocolsCommands[]
      created_at: string | Date
      description?: string
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
