// TypesFromSerializers CacheKey f4ce2151332c25bf86aba667043061e2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type CommandsProtocol from '../Commands/Protocol'

declare global {
  namespace Schema {
    interface ProtocolsShow {
      id: number
      commands: CommandsProtocol[]
      created_at: string | Date
      description?: string
      slug: string
      title: string
      updated_at: string | Date
    }
  }
}
