// TypesFromSerializers CacheKey eb0eb47068d42bb1d58514fe37209339
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtcolsCommandsEdit {
      id: unknown
      command_id: unknown
      created_at: unknown
      delay: unknown
      protocol_id: unknown
      updated_at: unknown
      value: unknown
    }
  }
}
