// TypesFromSerializers CacheKey 32e76085de68aab42a4a92ec2cb8bef0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtcolsCommandsFormData {
      id?: unknown
      command_id: unknown
      delay: unknown
      protocol_id: unknown
      value: unknown
    }
  }
}
