// TypesFromSerializers CacheKey 61be6e9c51b1a42278ded53d3fb7addb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtcolsCommandsIndex {
      id: unknown
      command_id: unknown
      created_at: unknown
      delay: unknown
      protocol_id: unknown
      updated_at: unknown
      value: unknown
    }
  }
}
