// TypesFromSerializers CacheKey 6c4914c091d533b67c265141f4a51e64
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ProtcolsCommandsShow {
      id: unknown
      command_id: unknown
      created_at: unknown
      delay: unknown
      protocol_id: unknown
      updated_at: unknown
      value: unknown
    }
  }
}
