// TypesFromSerializers CacheKey 2682b7a69440c6bd530713d3e0aa662b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteEndpointsEdit {
      id: number
      created_at: string | Date
      endpoint?: string
      remote_api_id: number
      title?: string
      updated_at: string | Date
    }
  }
}
