// TypesFromSerializers CacheKey 33f7b99934b13de1f951de81831e9549
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteEndpointsFormData {
      id?: number
      endpoint?: string
      remote_api_id: number
      title?: string
    }
  }
}
