// TypesFromSerializers CacheKey 04224286822d3d6e2fbddfe6ed5b00a2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteEndpointsIndex {
      id: number
      created_at: string | Date
      endpoint?: string
      remote_api_id: number
      title?: string
      updated_at: string | Date
    }
  }
}
