// TypesFromSerializers CacheKey eacb43c4b07d10a609a09d570d63dffa
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface RemoteEndpointsShow {
      id: number
      created_at: string | Date
      endpoint?: string
      remote_api_id: number
      title?: string
      updated_at: string | Date
    }
  }
}
